repos:
  - repo: https://github.com/kamadorueda/alejandra
    rev: 3.0.0
    # Choose either the 'alejandra' or 'alejandra-system' hook
    # depending on what pre-requisites you have:
    hooks:
      # No prerequisites
      - id: alejandra-system
