# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.15.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]
  - repo: https://github.com/kamadorueda/alejandra
    rev: 3.0.0
    hooks:
      # No prerequisites
      # - id: alejandra

      # Requires Nix to be previously installed in the system
      # - id: alejandra-nix

      # Requires Alejandra to be previously installed in the system
      - id: alejandra-system
