name: Prelude

on:
  workflow_call:
    inputs:
      command:
        required: false
        type: string
      platform:
        default: "ubuntu"
        required: false
        type: string
    # secrets:
    #   GH_TOKEN:
    #     required: true

jobs:
  nix:
    runs-on: "${{ inputs.platform }}-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        # with:
        #   token: "${{ secrets.GH_TOKEN }}"

      # - name: "Set up QEMU support"
      #   run: |
      #     export DEBIAN_FRONTEND=noninteractive
      #     sudo apt-get update -q -y
      #     sudo apt-get install -q -y binfmt-support qemu-efi qemu-system-aarch64 qemu-user-static

      - name: "Install nix"
        uses: cachix/install-nix-action@master
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            experimental-features = nix-command flakes fetch-tree
            allow-import-from-derivation = false
            extra-platforms = aarch64-linux

      - name: "Nix Magic Cache"
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: "Run Input: ${{ inputs.command }}"
        run: "${{ inputs.command }}"
